= Cloud Native Application Architectures with Spring and Cloud Foundry

Student Guide

== Instructor Details

Bjorn Boe +
Senior Field Engineer - Pivotal +
bboe@pivotal.io

Wes Hewatt +
Senior Field Engineer - Pivotal +
whewatt@pivotal.io

Michael Wright +
Field Engineering Manager - Pivotal +
mwright@pivotal.io

== Schedule

This is a _loose_ schedule for the day. We will adjust as necessary based on our pace through the material.

The lectures for this class are intentionally very light and are only intended to set the stage for the hands-on labs.
The overwhelming majority of our time will be spent engaging with the technology directly!

NOTE: We will be updating the course materials throughout the class. You will need to have the materials cloned and track the `customer` branch.

This can be accomplished as follows:

----
$ git clone https://github.com/whewatt-pivotal/SpringCloudWorkshop
$ git fetch --all
$ git checkout customer
----

=== Day One

8:00 AM - 9:30 AM:: *Session 1:* _Intro to Pivotal Cloud Foundry_
9:30 AM - 10:00 AM:: Morning Break
10:00 AM - 10:15 AM:: *Session 3:* _Custom Buildpacks_
10:15 AM - 11:00 AM:: *Session 4:*  _Spring Data on Cloud Foundry_
11:00 AM - 11:30 AM:: *Session 5:* _Spring Boot Actuator_
11:30 PM - 12:30 PM:: Lunch
12:30 PM - 1:30 PM:: *Session 6:* _Spring Config Server & Eureka on Cloud Foundry_
1:30 PM - 2:00 PM:: *Session 7:* _Angular JS & Hystrix Demo_
2:00 PM - 2:30 PM:: Afternoon Break
2:30 PM - 5:00 PM:: *Session 8:* _TBD:  Something with OAuth?_

== Course Materials

* Session 1 (link:session_01/session_01.pdf[Slides])
** link:session_01/lab_01/lab_01.adoc[Lab 1 - From Zero to Pushing Your First Application]
** link:session_01/lab_02/lab_02.adoc[Lab 2 - Binding to Cloud Foundry Services]
** link:session_01/lab_03/lab_03.adoc[Lab 3 - Scaling Applications]
** link:session_01/lab_04/lab_04.adoc[Lab 4 - Monitoring Applications]
* Session 3 (link:session_03/session_03.pdf[Slides])
* Session 4
** link:session_04/lab_05/lab_05.html[Lab 5 - Build a Hypermedia-Driven RESTful Web Service with Spring Data REST]
** link:session_04/lab_06/lab_06.html[Lab 6 - Leveraging Spring Cloud Connectors for Service Binding]
* Session 5 (link:session_05/session_05.pdf[Slides])
** link:session_05/lab_07/lab_07.html[Lab 7 - Introspection, Monitoring, and Metrics using Spring Boot Actuator]


